# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_table_data(self) -> None:
        """Test case for get_table_data

        Get Table Data
        """
        pass

    def test_get_table_names(self) -> None:
        """Test case for get_table_names

        Get Table Name
        """
        pass

    def test_post_mouse_weight_record(self) -> None:
        """Test case for post_mouse_weight_record

        Post Weight Record
        """
        pass

    def test_validate_email_in_system_users(self) -> None:
        """Test case for validate_email_in_system_users

        Validate Email in Users Table, Return Data
        """
        pass

    def test_validate_mouse_guidin_mouse_registry(self) -> None:
        """Test case for validate_mouse_guidin_mouse_registry

        validate mouseGUID in Mouse Registry, return data
        """
        pass

    def test_validate_mouse_idin_mouse_registry(self) -> None:
        """Test case for validate_mouse_idin_mouse_registry

        Validate Mouse ID in Mouse Registry
        """
        pass

    def test_validate_mouse_in_behavior_training(self) -> None:
        """Test case for validate_mouse_in_behavior_training

        validate mouse in Behavior Training, return data
        """
        pass

    def test_validate_mouse_in_water_restricted_mice_table(self) -> None:
        """Test case for validate_mouse_in_water_restricted_mice_table

        Validate Mouse Active in Water Restriction, Return Data
        """
        pass

    def test_water_restriction_post_baseline_weight(self) -> None:
        """Test case for water_restriction_post_baseline_weight

        Post Baseline Weight
        """
        pass

    def test_water_restriction_post_weight_and_water_records(self) -> None:
        """Test case for water_restriction_post_weight_and_water_records

        Post Weight and Water Record
        """
        pass

    def test_water_restriction_update_restriction_status(self) -> None:
        """Test case for water_restriction_update_restriction_status

        Update Water Restriction Status
        """
        pass

    def test_water_restriction_update_target_weight_percent(self) -> None:
        """Test case for water_restriction_update_target_weight_percent

        Update Target Weight Percent
        """
        pass


if __name__ == '__main__':
    unittest.main()
