# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_mouse_in_behavior_training_default_response import ValidateMouseInBehaviorTrainingDefaultResponse

class TestValidateMouseInBehaviorTrainingDefaultResponse(unittest.TestCase):
    """ValidateMouseInBehaviorTrainingDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMouseInBehaviorTrainingDefaultResponse:
        """Test ValidateMouseInBehaviorTrainingDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMouseInBehaviorTrainingDefaultResponse`
        """
        model = ValidateMouseInBehaviorTrainingDefaultResponse()
        if include_optional:
            return ValidateMouseInBehaviorTrainingDefaultResponse(
                status_code = 56,
                status_message = '',
                behavior_training_guid = '',
                active_record = True,
                mouse_guid = '',
                mouse_id = '',
                project_guid = '',
                project_name = '',
                project_code = '',
                training_protocol = '',
                mouse_assignment_status_choice_value = 56,
                mouse_assignment_status_choice_label = '',
                assigned_trainer_userguid = '',
                assigned_trainer_name = '',
                assigned_trainer_email = '',
                backup_trainer_userguid = '',
                backup_trainer_name = '',
                backup_trainer_email = '',
                scientific_contact_userguid = '',
                scientific_contact_name = '',
                scientific_contact_email = '',
                water_restriction_guid = ''
            )
        else:
            return ValidateMouseInBehaviorTrainingDefaultResponse(
        )
        """

    def testValidateMouseInBehaviorTrainingDefaultResponse(self):
        """Test ValidateMouseInBehaviorTrainingDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
