# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.water_restriction_post_weight_and_water_records_request import WaterRestrictionPostWeightAndWaterRecordsRequest

class TestWaterRestrictionPostWeightAndWaterRecordsRequest(unittest.TestCase):
    """WaterRestrictionPostWeightAndWaterRecordsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WaterRestrictionPostWeightAndWaterRecordsRequest:
        """Test WaterRestrictionPostWeightAndWaterRecordsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WaterRestrictionPostWeightAndWaterRecordsRequest`
        """
        model = WaterRestrictionPostWeightAndWaterRecordsRequest()
        if include_optional:
            return WaterRestrictionPostWeightAndWaterRecordsRequest(
                date_time = '',
                mouse_id = '',
                mouse_guid = '',
                water_restriction_guid = '',
                team_guid = '',
                operator_user_guid = '',
                water_total = 1.337,
                water_supplemental_provided = 1.337,
                water_supplemental_recommended = 1.337,
                water_task = 56,
                weight = 1.337,
                is_baseline_weight = True,
                notes = '',
                software_source = '',
                workstation = '',
                software_version = ''
            )
        else:
            return WaterRestrictionPostWeightAndWaterRecordsRequest(
        )
        """

    def testWaterRestrictionPostWeightAndWaterRecordsRequest(self):
        """Test WaterRestrictionPostWeightAndWaterRecordsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
