# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_email_in_system_users_default_response import ValidateEmailInSystemUsersDefaultResponse

class TestValidateEmailInSystemUsersDefaultResponse(unittest.TestCase):
    """ValidateEmailInSystemUsersDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateEmailInSystemUsersDefaultResponse:
        """Test ValidateEmailInSystemUsersDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateEmailInSystemUsersDefaultResponse`
        """
        model = ValidateEmailInSystemUsersDefaultResponse()
        if include_optional:
            return ValidateEmailInSystemUsersDefaultResponse(
                status_code = 56,
                status_message = '',
                user_guid = '',
                full_name = '',
                email_address = ''
            )
        else:
            return ValidateEmailInSystemUsersDefaultResponse(
        )
        """

    def testValidateEmailInSystemUsersDefaultResponse(self):
        """Test ValidateEmailInSystemUsersDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
