# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.water_restriction_post_baseline_weight_request import WaterRestrictionPostBaselineWeightRequest

class TestWaterRestrictionPostBaselineWeightRequest(unittest.TestCase):
    """WaterRestrictionPostBaselineWeightRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WaterRestrictionPostBaselineWeightRequest:
        """Test WaterRestrictionPostBaselineWeightRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WaterRestrictionPostBaselineWeightRequest`
        """
        model = WaterRestrictionPostBaselineWeightRequest()
        if include_optional:
            return WaterRestrictionPostBaselineWeightRequest(
                water_restriction_guid = '',
                baseline_weight = 1.337
            )
        else:
            return WaterRestrictionPostBaselineWeightRequest(
        )
        """

    def testWaterRestrictionPostBaselineWeightRequest(self):
        """Test WaterRestrictionPostBaselineWeightRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
