# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.water_restriction_update_restriction_status_request import WaterRestrictionUpdateRestrictionStatusRequest

class TestWaterRestrictionUpdateRestrictionStatusRequest(unittest.TestCase):
    """WaterRestrictionUpdateRestrictionStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WaterRestrictionUpdateRestrictionStatusRequest:
        """Test WaterRestrictionUpdateRestrictionStatusRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WaterRestrictionUpdateRestrictionStatusRequest`
        """
        model = WaterRestrictionUpdateRestrictionStatusRequest()
        if include_optional:
            return WaterRestrictionUpdateRestrictionStatusRequest(
                water_restriction_guid = '',
                updated_water_restriction_status = ''
            )
        else:
            return WaterRestrictionUpdateRestrictionStatusRequest(
        )
        """

    def testWaterRestrictionUpdateRestrictionStatusRequest(self):
        """Test WaterRestrictionUpdateRestrictionStatusRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
