# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_mouse_guidin_mouse_registry_request import ValidateMouseGUIDInMouseRegistryRequest

class TestValidateMouseGUIDInMouseRegistryRequest(unittest.TestCase):
    """ValidateMouseGUIDInMouseRegistryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMouseGUIDInMouseRegistryRequest:
        """Test ValidateMouseGUIDInMouseRegistryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMouseGUIDInMouseRegistryRequest`
        """
        model = ValidateMouseGUIDInMouseRegistryRequest()
        if include_optional:
            return ValidateMouseGUIDInMouseRegistryRequest(
                mouse_guid = ''
            )
        else:
            return ValidateMouseGUIDInMouseRegistryRequest(
        )
        """

    def testValidateMouseGUIDInMouseRegistryRequest(self):
        """Test ValidateMouseGUIDInMouseRegistryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
