# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_email_in_users_return_data_request import ValidateEmailInUsersReturnDataRequest

class TestValidateEmailInUsersReturnDataRequest(unittest.TestCase):
    """ValidateEmailInUsersReturnDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateEmailInUsersReturnDataRequest:
        """Test ValidateEmailInUsersReturnDataRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateEmailInUsersReturnDataRequest`
        """
        model = ValidateEmailInUsersReturnDataRequest()
        if include_optional:
            return ValidateEmailInUsersReturnDataRequest(
                email_address = ''
            )
        else:
            return ValidateEmailInUsersReturnDataRequest(
        )
        """

    def testValidateEmailInUsersReturnDataRequest(self):
        """Test ValidateEmailInUsersReturnDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
