# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_mouse_idin_mouse_registry_request import ValidateMouseIDInMouseRegistryRequest

class TestValidateMouseIDInMouseRegistryRequest(unittest.TestCase):
    """ValidateMouseIDInMouseRegistryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMouseIDInMouseRegistryRequest:
        """Test ValidateMouseIDInMouseRegistryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMouseIDInMouseRegistryRequest`
        """
        model = ValidateMouseIDInMouseRegistryRequest()
        if include_optional:
            return ValidateMouseIDInMouseRegistryRequest(
                mouse_id = ''
            )
        else:
            return ValidateMouseIDInMouseRegistryRequest(
        )
        """

    def testValidateMouseIDInMouseRegistryRequest(self):
        """Test ValidateMouseIDInMouseRegistryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
