# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.post_mouse_weight_record_request import PostMouseWeightRecordRequest

class TestPostMouseWeightRecordRequest(unittest.TestCase):
    """PostMouseWeightRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostMouseWeightRecordRequest:
        """Test PostMouseWeightRecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostMouseWeightRecordRequest`
        """
        model = PostMouseWeightRecordRequest()
        if include_optional:
            return PostMouseWeightRecordRequest(
                mouse_id = '',
                mouse_guid = '',
                weight = 1.337,
                is_baseline_weight = True,
                date_time = '',
                operator_user_guid = '',
                notes = '',
                workstation = '',
                software_source = '',
                software_version = ''
            )
        else:
            return PostMouseWeightRecordRequest(
        )
        """

    def testPostMouseWeightRecordRequest(self):
        """Test PostMouseWeightRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
