# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_mouse_in_water_restricted_mice_table_request import ValidateMouseInWaterRestrictedMiceTableRequest

class TestValidateMouseInWaterRestrictedMiceTableRequest(unittest.TestCase):
    """ValidateMouseInWaterRestrictedMiceTableRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMouseInWaterRestrictedMiceTableRequest:
        """Test ValidateMouseInWaterRestrictedMiceTableRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMouseInWaterRestrictedMiceTableRequest`
        """
        model = ValidateMouseInWaterRestrictedMiceTableRequest()
        if include_optional:
            return ValidateMouseInWaterRestrictedMiceTableRequest(
                mouse_guid = '',
                mouse_id = ''
            )
        else:
            return ValidateMouseInWaterRestrictedMiceTableRequest(
        )
        """

    def testValidateMouseInWaterRestrictedMiceTableRequest(self):
        """Test ValidateMouseInWaterRestrictedMiceTableRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
