# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_mouse_guidin_mouse_registry_default_response import ValidateMouseGUIDInMouseRegistryDefaultResponse

class TestValidateMouseGUIDInMouseRegistryDefaultResponse(unittest.TestCase):
    """ValidateMouseGUIDInMouseRegistryDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMouseGUIDInMouseRegistryDefaultResponse:
        """Test ValidateMouseGUIDInMouseRegistryDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMouseGUIDInMouseRegistryDefaultResponse`
        """
        model = ValidateMouseGUIDInMouseRegistryDefaultResponse()
        if include_optional:
            return ValidateMouseGUIDInMouseRegistryDefaultResponse(
                status_code = 56,
                status_message = '',
                mouse_guid = '',
                mouse_id = '',
                sex = '',
                date_of_birth = '',
                date_of_death = '',
                deceased = True,
                reverse_light_cycle = True,
                project_guid = '',
                project_name = '',
                iacuc_guid = '',
                iacuc_protocol = '',
                genotype = ''
            )
        else:
            return ValidateMouseGUIDInMouseRegistryDefaultResponse(
        )
        """

    def testValidateMouseGUIDInMouseRegistryDefaultResponse(self):
        """Test ValidateMouseGUIDInMouseRegistryDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
