# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_mouse_in_water_restricted_mice_table_default_response import ValidateMouseInWaterRestrictedMiceTableDefaultResponse

class TestValidateMouseInWaterRestrictedMiceTableDefaultResponse(unittest.TestCase):
    """ValidateMouseInWaterRestrictedMiceTableDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateMouseInWaterRestrictedMiceTableDefaultResponse:
        """Test ValidateMouseInWaterRestrictedMiceTableDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateMouseInWaterRestrictedMiceTableDefaultResponse`
        """
        model = ValidateMouseInWaterRestrictedMiceTableDefaultResponse()
        if include_optional:
            return ValidateMouseInWaterRestrictedMiceTableDefaultResponse(
                status_code = 56,
                status_message = '',
                waterrestrictionguid = '',
                activerecord = True,
                mouseguid = '',
                mouseid = '',
                baseline_weight = 1.337,
                target_weight_percentage = 1.337,
                target_weight = 1.337,
                low_weight_threshold = 1.337,
                team_guid = '',
                team_name = '',
                behavior_training_guid = '',
                watering_shift_value = 56,
                watering_shift_label = '',
                water_restriction_status_value = 56,
                water_restriction_status_label = '',
                watered_today = True,
                last_watered_datetime = '',
                record_name = ''
            )
        else:
            return ValidateMouseInWaterRestrictedMiceTableDefaultResponse(
        )
        """

    def testValidateMouseInWaterRestrictedMiceTableDefaultResponse(self):
        """Test ValidateMouseInWaterRestrictedMiceTableDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
