# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.validate_email_in_users_return_data_default_response import ValidateEmailInUsersReturnDataDefaultResponse

class TestValidateEmailInUsersReturnDataDefaultResponse(unittest.TestCase):
    """ValidateEmailInUsersReturnDataDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateEmailInUsersReturnDataDefaultResponse:
        """Test ValidateEmailInUsersReturnDataDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateEmailInUsersReturnDataDefaultResponse`
        """
        model = ValidateEmailInUsersReturnDataDefaultResponse()
        if include_optional:
            return ValidateEmailInUsersReturnDataDefaultResponse(
                status_code = 56,
                status_message = '',
                user_guid = '',
                full_name = '',
                email_address = ''
            )
        else:
            return ValidateEmailInUsersReturnDataDefaultResponse(
        )
        """

    def testValidateEmailInUsersReturnDataDefaultResponse(self):
        """Test ValidateEmailInUsersReturnDataDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
