# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetTableDataRequest(BaseModel):
    """
    GetTableDataRequest
    """ # noqa: E501
    table_name: Optional[StrictStr] = Field(default=None, description="table_name")
    columns: Optional[StrictStr] = Field(default=None, description="columns")
    filter: Optional[StrictStr] = Field(default=None, description="filter")
    order_by: Optional[StrictStr] = Field(default=None, description="order_by")
    fetch_xml: Optional[StrictStr] = Field(default=None, description="fetch_xml")
    row_count: Optional[StrictInt] = Field(default=None, description="row_count")
    __properties: ClassVar[List[str]] = ["table_name", "columns", "filter", "order_by", "fetch_xml", "row_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTableDataRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTableDataRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "table_name": obj.get("table_name"),
            "columns": obj.get("columns"),
            "filter": obj.get("filter"),
            "order_by": obj.get("order_by"),
            "fetch_xml": obj.get("fetch_xml"),
            "row_count": obj.get("row_count")
        })
        return _obj


