# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ValidateMouseInWaterRestrictedMiceTableDefaultResponse(BaseModel):
    """
    ValidateMouseInWaterRestrictedMiceTableDefaultResponse
    """ # noqa: E501
    status_code: Optional[StrictInt] = Field(default=None, description="status_code")
    status_message: Optional[StrictStr] = Field(default=None, description="status_message")
    waterrestrictionguid: Optional[StrictStr] = Field(default=None, description="waterrestrictionguid")
    activerecord: Optional[StrictBool] = Field(default=None, description="activerecord")
    mouseguid: Optional[StrictStr] = Field(default=None, description="mouseguid")
    mouseid: Optional[StrictStr] = Field(default=None, description="mouseid")
    baseline_weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="baseline_weight")
    target_weight_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="target_weight_percentage")
    target_weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="target_weight")
    low_weight_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="low_weight_threshold")
    team_guid: Optional[StrictStr] = Field(default=None, description="team_guid")
    team_name: Optional[StrictStr] = Field(default=None, description="team_name")
    behavior_training_guid: Optional[StrictStr] = Field(default=None, description="behavior_training_guid")
    watering_shift_value: Optional[StrictInt] = Field(default=None, description="watering_shift_value")
    watering_shift_label: Optional[StrictStr] = Field(default=None, description="watering_shift_label")
    water_restriction_status_value: Optional[StrictInt] = Field(default=None, description="water_restriction_status_value")
    water_restriction_status_label: Optional[StrictStr] = Field(default=None, description="water_restriction_status_label")
    watered_today: Optional[StrictBool] = Field(default=None, description="watered_today")
    last_watered_datetime: Optional[StrictStr] = Field(default=None, description="last_watered_datetime")
    record_name: Optional[StrictStr] = Field(default=None, description="record_name")
    __properties: ClassVar[List[str]] = ["status_code", "status_message", "waterrestrictionguid", "activerecord", "mouseguid", "mouseid", "baseline_weight", "target_weight_percentage", "target_weight", "low_weight_threshold", "team_guid", "team_name", "behavior_training_guid", "watering_shift_value", "watering_shift_label", "water_restriction_status_value", "water_restriction_status_label", "watered_today", "last_watered_datetime", "record_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidateMouseInWaterRestrictedMiceTableDefaultResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidateMouseInWaterRestrictedMiceTableDefaultResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status_code": obj.get("status_code"),
            "status_message": obj.get("status_message"),
            "waterrestrictionguid": obj.get("waterrestrictionguid"),
            "activerecord": obj.get("activerecord"),
            "mouseguid": obj.get("mouseguid"),
            "mouseid": obj.get("mouseid"),
            "baseline_weight": obj.get("baseline_weight"),
            "target_weight_percentage": obj.get("target_weight_percentage"),
            "target_weight": obj.get("target_weight"),
            "low_weight_threshold": obj.get("low_weight_threshold"),
            "team_guid": obj.get("team_guid"),
            "team_name": obj.get("team_name"),
            "behavior_training_guid": obj.get("behavior_training_guid"),
            "watering_shift_value": obj.get("watering_shift_value"),
            "watering_shift_label": obj.get("watering_shift_label"),
            "water_restriction_status_value": obj.get("water_restriction_status_value"),
            "water_restriction_status_label": obj.get("water_restriction_status_label"),
            "watered_today": obj.get("watered_today"),
            "last_watered_datetime": obj.get("last_watered_datetime"),
            "record_name": obj.get("record_name")
        })
        return _obj


