# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ValidateMouseIDInMouseRegistryDefaultResponse(BaseModel):
    """
    ValidateMouseIDInMouseRegistryDefaultResponse
    """ # noqa: E501
    status_code: Optional[StrictInt] = Field(default=None, description="StatusCode", alias="StatusCode")
    status_message: Optional[StrictStr] = Field(default=None, description="StatusMessage", alias="StatusMessage")
    mouse_guid: Optional[StrictStr] = Field(default=None, description="MouseGUID", alias="MouseGUID")
    mouse_id: Optional[StrictStr] = Field(default=None, description="MouseID", alias="MouseID")
    sex: Optional[StrictStr] = Field(default=None, description="Sex", alias="Sex")
    date_of_birth: Optional[StrictStr] = Field(default=None, description="DateOfBirth", alias="DateOfBirth")
    date_of_death: Optional[StrictStr] = Field(default=None, description="DateOfDeath", alias="DateOfDeath")
    deceased: Optional[StrictStr] = Field(default=None, description="Deceased", alias="Deceased")
    reverse_light_cycle: Optional[StrictStr] = Field(default=None, description="ReverseLightCycle", alias="ReverseLightCycle")
    project_guid: Optional[StrictStr] = Field(default=None, description="ProjectGUID", alias="ProjectGUID")
    project_name: Optional[StrictStr] = Field(default=None, description="ProjectName", alias="ProjectName")
    iacuc_guid: Optional[StrictStr] = Field(default=None, description="IACUC GUID", alias="IACUC GUID")
    iacuc_protocol: Optional[StrictStr] = Field(default=None, description="IACUCProtocol", alias="IACUCProtocol")
    genotype: Optional[StrictStr] = Field(default=None, description="Genotype", alias="Genotype")
    __properties: ClassVar[List[str]] = ["StatusCode", "StatusMessage", "MouseGUID", "MouseID", "Sex", "DateOfBirth", "DateOfDeath", "Deceased", "ReverseLightCycle", "ProjectGUID", "ProjectName", "IACUC GUID", "IACUCProtocol", "Genotype"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidateMouseIDInMouseRegistryDefaultResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidateMouseIDInMouseRegistryDefaultResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "StatusCode": obj.get("StatusCode"),
            "StatusMessage": obj.get("StatusMessage"),
            "MouseGUID": obj.get("MouseGUID"),
            "MouseID": obj.get("MouseID"),
            "Sex": obj.get("Sex"),
            "DateOfBirth": obj.get("DateOfBirth"),
            "DateOfDeath": obj.get("DateOfDeath"),
            "Deceased": obj.get("Deceased"),
            "ReverseLightCycle": obj.get("ReverseLightCycle"),
            "ProjectGUID": obj.get("ProjectGUID"),
            "ProjectName": obj.get("ProjectName"),
            "IACUC GUID": obj.get("IACUC GUID"),
            "IACUCProtocol": obj.get("IACUCProtocol"),
            "Genotype": obj.get("Genotype")
        })
        return _obj


