# coding: utf-8

"""
    Default title

    This custom connector is configured to interact with development environment flows and is intended for use during active development, testing, and validation.  It points to HTTP-triggered flows deployed in the development environment and is updated frequently as APIs evolve. This connector may reference non-final endpoints, in-progress schemas, and experimental logic.  Because development flow URLs are environment-specific and subject to change, this connector should only be used in dev solution

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class WaterRestrictionPostWeightAndWaterRecordsRequest(BaseModel):
    """
    WaterRestrictionPostWeightAndWaterRecordsRequest
    """ # noqa: E501
    date_time: Optional[StrictStr] = Field(default=None, description="date_time")
    mouse_id: Optional[StrictStr] = Field(default=None, description="mouse_ID", alias="mouse_ID")
    mouse_guid: Optional[StrictStr] = Field(default=None, description="mouse_GUID", alias="mouse_GUID")
    water_restriction_guid: Optional[StrictStr] = Field(default=None, description="water_restriction_GUID", alias="water_restriction_GUID")
    team_guid: Optional[StrictStr] = Field(default=None, description="team_GUID", alias="team_GUID")
    operator_user_guid: Optional[StrictStr] = Field(default=None, description="operator_userGUID", alias="operator_userGUID")
    water_total: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="water_total")
    water_supplemental_provided: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="water_supplemental_provided")
    water_supplemental_recommended: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="water_supplemental_recommended")
    water_task: Optional[StrictInt] = Field(default=None, description="water_task")
    weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="weight")
    is_baseline_weight: Optional[StrictBool] = Field(default=None, description="is_baseline_weight")
    notes: Optional[StrictStr] = Field(default=None, description="notes")
    software_source: Optional[StrictStr] = Field(default=None, description="software_source")
    workstation: Optional[StrictStr] = Field(default=None, description="workstation")
    software_version: Optional[StrictStr] = Field(default=None, description="software_version")
    __properties: ClassVar[List[str]] = ["date_time", "mouse_ID", "mouse_GUID", "water_restriction_GUID", "team_GUID", "operator_userGUID", "water_total", "water_supplemental_provided", "water_supplemental_recommended", "water_task", "weight", "is_baseline_weight", "notes", "software_source", "workstation", "software_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WaterRestrictionPostWeightAndWaterRecordsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WaterRestrictionPostWeightAndWaterRecordsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_time": obj.get("date_time"),
            "mouse_ID": obj.get("mouse_ID"),
            "mouse_GUID": obj.get("mouse_GUID"),
            "water_restriction_GUID": obj.get("water_restriction_GUID"),
            "team_GUID": obj.get("team_GUID"),
            "operator_userGUID": obj.get("operator_userGUID"),
            "water_total": obj.get("water_total"),
            "water_supplemental_provided": obj.get("water_supplemental_provided"),
            "water_supplemental_recommended": obj.get("water_supplemental_recommended"),
            "water_task": obj.get("water_task"),
            "weight": obj.get("weight"),
            "is_baseline_weight": obj.get("is_baseline_weight"),
            "notes": obj.get("notes"),
            "software_source": obj.get("software_source"),
            "workstation": obj.get("workstation"),
            "software_version": obj.get("software_version")
        })
        return _obj


