# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PostMouseWeightRecordRequest(BaseModel):
    """
    PostMouseWeightRecordRequest
    """ # noqa: E501
    mouse_id: Optional[StrictStr] = Field(default=None, description="mouse_ID", alias="mouse_ID")
    mouse_guid: Optional[StrictStr] = Field(default=None, description="mouse_GUID", alias="mouse_GUID")
    weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="weight")
    is_baseline_weight: Optional[StrictBool] = Field(default=None, description="is_baseline_weight")
    date_time: Optional[StrictStr] = Field(default=None, description="date_time")
    operator_user_guid: Optional[StrictStr] = Field(default=None, description="operator_userGUID", alias="operator_userGUID")
    notes: Optional[StrictStr] = Field(default=None, description="notes")
    workstation: Optional[StrictStr] = Field(default=None, description="workstation")
    software_source: Optional[StrictStr] = Field(default=None, description="software_source")
    software_version: Optional[StrictStr] = Field(default=None, description="software_version")
    __properties: ClassVar[List[str]] = ["mouse_ID", "mouse_GUID", "weight", "is_baseline_weight", "date_time", "operator_userGUID", "notes", "workstation", "software_source", "software_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostMouseWeightRecordRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostMouseWeightRecordRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mouse_ID": obj.get("mouse_ID"),
            "mouse_GUID": obj.get("mouse_GUID"),
            "weight": obj.get("weight"),
            "is_baseline_weight": obj.get("is_baseline_weight"),
            "date_time": obj.get("date_time"),
            "operator_userGUID": obj.get("operator_userGUID"),
            "notes": obj.get("notes"),
            "workstation": obj.get("workstation"),
            "software_source": obj.get("software_source"),
            "software_version": obj.get("software_version")
        })
        return _obj


