# coding: utf-8

"""
    Default title

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ValidateMouseInBehaviorTrainingDefaultResponse(BaseModel):
    """
    ValidateMouseInBehaviorTrainingDefaultResponse
    """ # noqa: E501
    status_code: Optional[StrictInt] = Field(default=None, description="status_code")
    status_message: Optional[StrictStr] = Field(default=None, description="status_message")
    behavior_training_guid: Optional[StrictStr] = Field(default=None, description="behavior_training_guid")
    active_record: Optional[StrictBool] = Field(default=None, description="active_record")
    mouse_guid: Optional[StrictStr] = Field(default=None, description="mouse_guid")
    mouse_id: Optional[StrictStr] = Field(default=None, description="mouse_id")
    project_guid: Optional[StrictStr] = Field(default=None, description="project_guid")
    project_name: Optional[StrictStr] = Field(default=None, description="project_name")
    project_code: Optional[StrictStr] = Field(default=None, description="project_code")
    training_protocol: Optional[StrictStr] = Field(default=None, description="training_protocol")
    mouse_assignment_status_choice_value: Optional[StrictInt] = Field(default=None, description="mouse_assignment_status_choice_value")
    mouse_assignment_status_choice_label: Optional[StrictStr] = Field(default=None, description="mouse_assignment_status_choice_label")
    assigned_trainer_userguid: Optional[StrictStr] = Field(default=None, description="assigned_trainer_userguid")
    assigned_trainer_name: Optional[StrictStr] = Field(default=None, description="assigned_trainer_name")
    assigned_trainer_email: Optional[StrictStr] = Field(default=None, description="assigned_trainer_email")
    backup_trainer_userguid: Optional[StrictStr] = Field(default=None, description="backup_trainer_userguid")
    backup_trainer_name: Optional[StrictStr] = Field(default=None, description="backup_trainer_name")
    backup_trainer_email: Optional[StrictStr] = Field(default=None, description="backup_trainer_email")
    scientific_contact_userguid: Optional[StrictStr] = Field(default=None, description="scientific_contact_userguid")
    scientific_contact_name: Optional[StrictStr] = Field(default=None, description="scientific_contact_name")
    scientific_contact_email: Optional[StrictStr] = Field(default=None, description="scientific_contact_email")
    water_restriction_guid: Optional[StrictStr] = Field(default=None, description="water_restriction_guid")
    __properties: ClassVar[List[str]] = ["status_code", "status_message", "behavior_training_guid", "active_record", "mouse_guid", "mouse_id", "project_guid", "project_name", "project_code", "training_protocol", "mouse_assignment_status_choice_value", "mouse_assignment_status_choice_label", "assigned_trainer_userguid", "assigned_trainer_name", "assigned_trainer_email", "backup_trainer_userguid", "backup_trainer_name", "backup_trainer_email", "scientific_contact_userguid", "scientific_contact_name", "scientific_contact_email", "water_restriction_guid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidateMouseInBehaviorTrainingDefaultResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidateMouseInBehaviorTrainingDefaultResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status_code": obj.get("status_code"),
            "status_message": obj.get("status_message"),
            "behavior_training_guid": obj.get("behavior_training_guid"),
            "active_record": obj.get("active_record"),
            "mouse_guid": obj.get("mouse_guid"),
            "mouse_id": obj.get("mouse_id"),
            "project_guid": obj.get("project_guid"),
            "project_name": obj.get("project_name"),
            "project_code": obj.get("project_code"),
            "training_protocol": obj.get("training_protocol"),
            "mouse_assignment_status_choice_value": obj.get("mouse_assignment_status_choice_value"),
            "mouse_assignment_status_choice_label": obj.get("mouse_assignment_status_choice_label"),
            "assigned_trainer_userguid": obj.get("assigned_trainer_userguid"),
            "assigned_trainer_name": obj.get("assigned_trainer_name"),
            "assigned_trainer_email": obj.get("assigned_trainer_email"),
            "backup_trainer_userguid": obj.get("backup_trainer_userguid"),
            "backup_trainer_name": obj.get("backup_trainer_name"),
            "backup_trainer_email": obj.get("backup_trainer_email"),
            "scientific_contact_userguid": obj.get("scientific_contact_userguid"),
            "scientific_contact_name": obj.get("scientific_contact_name"),
            "scientific_contact_email": obj.get("scientific_contact_email"),
            "water_restriction_guid": obj.get("water_restriction_guid")
        })
        return _obj


