# coding: utf-8

"""
    Power Platform Connector

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from allen_powerplatform_client.models.update_target_weight_percentage_request import UpdateTargetWeightPercentageRequest

class TestUpdateTargetWeightPercentageRequest(unittest.TestCase):
    """UpdateTargetWeightPercentageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTargetWeightPercentageRequest:
        """Test UpdateTargetWeightPercentageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTargetWeightPercentageRequest`
        """
        model = UpdateTargetWeightPercentageRequest()
        if include_optional:
            return UpdateTargetWeightPercentageRequest(
                mouse_guid = '',
                updated_percent = 1.337
            )
        else:
            return UpdateTargetWeightPercentageRequest(
        )
        """

    def testUpdateTargetWeightPercentageRequest(self):
        """Test UpdateTargetWeightPercentageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
